replicaCount: 2

image:
  repository: 152254703525.dkr.ecr.eu-west-1.amazonaws.com/nemesis #gcr.io/google-samples/gb-frontend
  tag: frontend
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80

redis:
  port: 6379 
  slaveEnabled: true

